### ISSUE TITLE
ERRO na importação da dependencia do JUnit-Jupiter

### ISSUE THREAD

**Issue by rodrigoosantoss** [rafaabc/teste-web-selenium-java#1]
Fála Rafael, blz?! Cara primeiro queria te parabenizar gostei bastante da estrutura do teu código. Por isso baixei e estou tentando ajustar o ambiente pra executá-lo. De primeira queria te dizer que, por algum motivo que eu nao pesquisei a fundo tem um bug do Intellij 2020.3 pra rodar a dependencia : 
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.7.0</version>

Depois de pesquisar ((https://intellij-support.jetbrains.com/hc/en-us/community/posts/360010037279-IntelliJ-2020-3-problem-with-JUnit5), ele so atualizou pq injetei este parâmetros abaixo, seguindo a sugestão do suporte da Intellij:
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.4.0</version>
        <relativePath/> 
    </parent>

Enfim, to te relatando isso mais pra tentar contribuir dado que podemos evoluir juntos e ajudarmos a todos... abraços

**Comment by rafaabc** [comment]
E aí @rodrigoosantoss!! Atualizei o arquivo e já está na main branch. Consegue conferir se a importação agora funciona sem problemas na versão do IntelliJ 2020.3 por favor?
